### ISSUE TITLE
Run the unit tests for the JS libary in a build matrix against all supported libraries

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-javascript#503] opened 2021-09-21 10:10 UTC
https://github.com/appsignal/integration-guide/blob/main/roadmap.md#frontend

**Comment by tombruijn** [comment] 2021-09-24 13:23
Duplicate of https://github.com/appsignal/appsignal-javascript/issues/484

**Closed by tombruijn** 2021-09-24 13:23 UTC
Labels: chore, roadmap
