### ISSUE TITLE
Error Boundary components redirects the full app to an empty component

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-javascript#471] opened 2021-03-04 10:05 UTC
While using this at the app top-level and every time there is an error it completely deletes the app HTML due to the fallback loading.

https://docs.appsignal.com/front-end/integrations/react.html

## To do

- [x] Add test scenario for this in the react test app to reproduce: https://github.com/appsignal/test-setups/tree/main/javascript/react
- [ ] Write a fix for this

**Comment by tombruijn** [comment] 2021-03-04 10:58
Moved this to the JavaScript integration repo, as it's a react issue. We will need to reproduce it and find a solution for it.

**Comment by tombruijn** [comment] 2022-01-07 10:00
I've updated the react test app in this PR: https://github.com/appsignal/test-setups/pull/46
I did not see it being replaced with an empty component, unless my fallback component itself was empty.

Maybe they've set up an empty fallback component, or it's wrapping their entire app that renders everything, which is fine, and some CSS/layout issues are causing this.

**Comment by tombruijn** [comment] 2022-01-11 15:13
Reading the conversation again I get this from it:

They don't get a "redirect", in like a HTTP redirect to an empty page. It renders a full empty page, because their fallback component is empty and the ErrorBoundary is at the top level. Not specifying a fallback component should resolve this.

**Comment by tombruijn** [comment] 2022-01-11 15:32
If I don't set a fallback component as an option, the page just rerenders to the initial state. I think that's what they mean as well when they say ["[the fallback option] is commented but still repaints it"](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700029456#part_id=comment-16410700029456-8191065598). That's a React thing, I think. That's not something we explicitly do.

So I'm not sure how it could render nothing (the redirect to an empty page) if no fallback component is set. It should only do that if a fallback component is set, but it doesn't render anything. In that case, use the fallback component to render an error message. That's what it's for.

@shairyar does the above research help? Can we close the issue?

**Comment by shairyar** [comment] 2022-03-16 11:56
After discussing it with Tom we decided to close it.

**Closed** 2022-03-16 11:56 UTC
Labels: bug, support
